### ISSUE TITLE
app hanging when quitting

### ISSUE THREAD

**Issue by sinsynplus** [sebleedelisle/ofxLaser#12]
i'm using the master version of ofxLaser together with of_v0.10.1, even tried the very new of_v0.11.0 on osx (10.15 with xcode 9.4.1 and 10.11 with 7.2) with a ether dream 2 dac and so far the addon compiles fine and works but when i quit the app it hangs with a rotating apple beachball..

xcode terminal saying..

> sendBytes : Network error: Invalid socket
> send fail, fewer bytes sent than expected : 0

i'm also using the ofxLaser 0.9.8 version with of_v0.9.8 which does not have that behaviour..

thanks for the great addon..

**Comment by sebleedelisle** [comment]
Thanks so much for the report, this should be fixed in the latest push. Ironically this bug was introduced when I massively improved the reliability of the rest of the etherdream network code 😊 

FYI I haven't tested the add-on at all with of_v0.11.0 yet but hope to do so in the coming weeks.
