### ISSUE TITLE
addon does not compile when using #define OF_USE_LEGACY_VECTOR_MATH 1

### ISSUE THREAD

**Issue by sinsynplus** [sebleedelisle/ofxLaser#14]
thanks a lot for the awesome addon..
i'm using the master version of ofxLaser together with of_v0.10.1 and for a larger project i have to use..
#define OF_USE_LEGACY_VECTOR_MATH 1
and i'm getting this error..
Undefined symbols for architecture x86_64:
  "ofxLaser::Manager::drawPoly(ofPolyline_<ofVec3f> const&, ofColor_<unsigned char> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)"
i also tried the addon version for 0.98 together with of_v0.10.1 but that causes a lot more of errors..

**Comment by sebleedelisle** [comment]
Hey @sinsynplus I'm glad it's useful! I've had a quick look at this but I have no idea how to fix it. It's something to do with the type of ofPolyline but as I don't fully understand how OF_USE_LEGACY_VECTOR_MATH works under the hood, I'm not sure how to fix it.

FWIW I'm not fully transitioned to glm::vec3 yet when I work and I don't generally get a problem - are you sure you need the OF_USE_LEGACY_VECTOR_MATH flag? 

If you have any luck figuring it out, let me know.

**Comment by sebleedelisle** [comment]
Could this be related to this bug : https://github.com/openframeworks/openFrameworks/issues/6463 in which case it may be worth trying with of11 (although I have yet to test ofxLaser on 11)

**Comment by sinsynplus** [comment]
thanks a lot for your quick reply and your help.. the issue remains with of_v0.11.0..
i probably have to remove/fix the legacy math in my code..

as far as i can tell your addon is working fine with of_v0.11.0.. although i did not connect my etherdream dac/laser the helloLaser example is compiling with OF_USE_LEGACY_VECTOR_MATH set to zero..

**Comment by sebleedelisle** [comment]
Gonna close this for now, unfortunately I don't know enough about how the legacy mode works to fix it.
