### ISSUE TITLE
drawLine not drawing horizontal lines

### ISSUE THREAD

**Issue by sinsynplus** [sebleedelisle/ofxLaser#15]
i noticed that drawLine does not work with horizontal lines..
`laser.drawLine(glm::vec2(0, 400), glm::vec2(800, 400), color);`
while this vertical line works..
`laser.drawLine(glm::vec2(400, 0), glm::vec2(400, 800), color);`
same problem when doing a polyline with only 2 points..
```
ofPolyline p;
p.addVertex(glm::vec3(0, 400, 0));
p.addVertex(glm::vec3(800, 400, 0));
p.draw();
laser.drawPoly(p, color);
```
for now i found a workaround by adding a 3rd point in the middle..
```
ofPolyline p;
p.addVertex(glm::vec3(0, 400, 0));
p.addVertex(glm::vec3(400, 400, 0));
p.addVertex(glm::vec3(800, 400, 0));
p.draw();
```
laser.drawPoly(p, color);
also works fine when the line is slightly rotated by using..
```
ofPushMatrix();
ofRotateDeg(1.0);
laser.drawLine(glm::vec2(0, 400), glm::vec2(800, 400), color);
ofPopMatrix();
```
i had no issues with the same code using of_v0.9.8..
thanks a million for the great work..

**Comment by sebleedelisle** [comment]
Oh that sounds weird. I can't seem to replicate it here, are you using
oF11?

**Comment by sinsynplus** [comment]
thanks for your quick answer..
i am working with of_v0.10.1 together with xcode 9.4.1 and osx 10.14.6
the issue came up using a function like this..
```
void ofApp::drawLaserGrid(float x, float y, float w, float h) {
    ofColor c;
    c = ofColor(lineColorR, lineColorG, lineColorB, lineAlpha);
    for(unsigned int i = 0; i <= h; i+=y) {
        ofDrawLine(0, i, w, i);
	laser.drawLine(ofPoint(0, i), ofPoint(w, i), c, OFXLASER_PROFILE_DEFAULT);
    }
    for(unsigned int j = 0; j <= w; j+=x) {
        ofDrawLine(j, 0, j, h);
	laser.drawLine(ofPoint(j, 0), ofPoint(j, h), c, OFXLASER_PROFILE_DEFAULT);
    }
}
```

**Comment by sebleedelisle** [comment]
I'm not sure if this is it but it's probably not a great idea to use
unsigned ints for i and j when x, y, w, and h are floats. Try changing i
and j to floats and see if it makes any difference.

Or if you could produce a standalone ofApp.cpp that demonstrates the
problem, that would be great. Thanks!

Seb

**Comment by sinsynplus** [comment]
thanks for the hint.. i tried using floats but unfortunately makes no difference..
i created a quick example based on example_HelloLaser.. for some strange reason it's reversed.. drawing no vertical lines now..
[src.zip](https://github.com/sebleedelisle/ofxLaser/files/4618908/src.zip)

**Comment by sebleedelisle** [comment]
Damn, I'm running it here and all my lines seem to be working... did you turn on the legacy vector math option? I've attached my screen, in case I'm missing something. 

When you say that drawing lines don't work, do you see nothing at all? In the preview window and the output? 

Could you try deleting all the .json files in your bin folder? Maybe back them up first, and send me them if that fixed the issue. 

![Screenshot 2020-05-13 at 18 51 18](https://user-images.githubusercontent.com/110866/81847304-52a74080-954b-11ea-975e-6af86e55a883.png)

**Comment by sinsynplus** [comment]
that is super strange..

legacy math is off.. i managed to fix all my issues..
also i delete the .json/.xml files after every compile..

your output looks right.. in my case i see the green lines but i'm missing (either the horizontal or the vertical) lines in the purple colored preview.. and the missing ones are also not drawn by the laser.. (i am using the etherdream dac)

<img width="1280" alt="Screenshot 2020-05-13 at 22 29 31" src="https://user-images.githubusercontent.com/2048934/81863093-f48a5580-956a-11ea-8837-cf2d00003571.png">
<img width="1280" alt="Screenshot 2020-05-13 at 22 30 17" src="https://user-images.githubusercontent.com/2048934/81863116-f9e7a000-956a-11ea-8413-06bfaba3f029.png">

anyway if it's working for you don't worry too much about this issue.. i am totally fine with just adding a 3rd point into my polylines.. thanks a lot for your help..

**Comment by sebleedelisle** [comment]
Ohhh it's happening for me now! The trick was to delete *my* json files haha. OK I'm on this now, thanks so much for letting me know.

**Comment by sebleedelisle** [comment]
I think I've got to the bottom of it - it's actually a bug in some oF code that tests if a line is inside a rectangle. The way to temporarily fix it at your end is by not going all the way to the edge of the input window, ie 0.1 instead of 0, 799.9 instead of 800. But I'll see about getting it fixed in oF in the meantime.

**Comment by sebleedelisle** [comment]
I've issued a pull request on openFrameworks that fixes this. Thanks for your help! 

https://github.com/openframeworks/openFrameworks/pull/6586
