### ISSUE TITLE
zone1warp function not working

### ISSUE THREAD

**Issue by iverson777** [sebleedelisle/ofxLaser#19]
this addons is awesome!!
thank you for sharing!!
as title, everything is good, but I can't not use "ZoneTransform" in "Zone1warp" interface.

**Comment by sebleedelisle** [comment]
thanks!

I'm not sure what you mean - can you explain? I probably need to add
instructions but as far as I know the zone transform system is working.

**Comment by iverson777** [comment]
Thank you for reply!!
I'm try to mapping projector screen and laser zone.
I thought Zone1warp can do something like warpIntoMe(like openCV).
or can you tell me how to use Zone1warp function in interface, thank you!!
by the way my platform is OSX  of_v0.10.1 and WINDOWS of_v0.11.0 control laser by etherdream.

**Comment by iverson777** [comment]
my bad, I found need set as currentProjector, in example project is press "TAB"
the addon is really awesome!!

**Comment by sebleedelisle** [comment]
Ah great, glad you figured it out. Sorry about the lack of documentation 😬 😊
