### ISSUE TITLE
Dac Etherdream: Vector subscript out of range

### ISSUE THREAD

**Issue by adminfriso** [sebleedelisle/ofxLaser#27]
https://github.com/sebleedelisle/ofxLaser/blob/ee8e81f4162e93f03908d7aeca0dc349ecce2b8d/src/dacs/ofxLaserDacEtherdream.cpp#L453

Hi Seb,
Im getting an error on this line. Vector subscript out of range.

I tried surrounding it with a try catch, but that ofcourse is not a good and permanent solution , and it does not even work.

I tried to check in the addPoint method if the point added to bufferedPoints is a nullpointer. but that does not work.
I found the comment // copy assignment hopefully!
Has there been issues there before or?

I dont know what the error is, or how to fix it. Im not sure when it triggers, sometimes it triggers when I send a lot of points, but it also triggers sometimes when i do not expect it. Its really strange, and I am out of options.

For your info: This is the code we use to send our points to the laser/dac. (In the update loop)

```
	laser.sendRawPoints(points, 0, 0);
	laser.sendRawPoints(points, 1, 1);
	laser.sendRawPoints(points, 2, 2);
	laser.sendRawPoints(pointsL0, 0, 0);
	laser.sendRawPoints(pointsL1, 1, 1);
	laser.sendRawPoints(pointsL2, 2, 2);

	points.clear();
	pointsL0.clear();
	pointsL1.clear();
	pointsL2.clear();

	//laser
	laser.update();
```

**Comment by sebleedelisle** [comment]
OK I'm on it 😊

**Comment by sebleedelisle** [comment]
Last commit fixes this, I was making assumptions about there being frame points (which there aren't if you're sending raw points). Thanks for your assistance! 

b89af1ed77657eb00fe87b8213826ff6cb0b6493

**Comment by adminfriso** [comment]
Works like a charm! Thank you verry much

**Comment by sebleedelisle** [comment]
you're welcome 😊
