### ISSUE TITLE
Unable to find compatible svgtiny builds for linux

### ISSUE THREAD

**Issue by ErikNatanael** [sebleedelisle/ofxLaser#28]
Hi!

I've been unable to find a build of libsvgtiny for linux64 that worked with the main branch. ofxSvgExtra doesn't include linux builds.
Trying to use [builds from the Arch repos](https://archlinux.pkgs.org/rolling/archlinux-community-x86_64/libsvgtiny-0.1.7-4-x86_64.pkg.tar.zst.html) I ran into problems with the dependencies (libdom and libwapcaplet) which would cause strange build  errors.

The 11.0.2 branch works fine.

OS: Ubuntu 21.04.

Have I overlooked an obvious solution to getting these libs on Ubuntu?

**Comment by sebleedelisle** [comment]
Oh hey, yeah I had that problem when I tried compiling on Raspberry Pi recently, can you try adding ofxSvg to your build and see if that helps? Thanks! 

Seb

**Comment by ErikNatanael** [comment]
I thought I'd done that, but that actually worked, thank you! And thanks for making this awesome library!

**Comment by sebleedelisle** [comment]
thank you! I'd love to hear what you're making with it.

**Comment by ErikNatanael** [comment]
I'll be sure to let you know once there's something to see :) It's for a rethread.art work.
