### ISSUE TITLE
Etherdream 3 soft restarting 

### ISSUE THREAD

**Issue by ErikNatanael** [sebleedelisle/ofxLaser#30]
Hi!

I'm not sure this is related to the library, but I thought I'd start here. Sometimes, at irregular intervals and frequencies, the Etherdream 3 DAC seems to soft restart and the following messages are posted in the terminal window of the ofxLaser app:
```
[notice ] response : I command : d

protocol           : 0
light_engine_state : ready 0
playback_state     : idle 0
source             : 0
light_engine_flags : 00000
playback_flags     : 000
source_flags       : 0
buffer_fullness    : 224
point_rate         : 0
point_count        : 15743447

[notice ] sendPrepare()
[notice ] sendBegin()
```
The visual result is ~one black frame every time it restarts, sometimes also with a dot at the top left corner of the laser. Any idea what might cause it and how to avoid it?

Thanks!

**Comment by sebleedelisle** [comment]
Hey Erik,

Ah I haven't tested the Ether Dream v3 very much yet, but I will do in the
coming weeks. It could be something specific to that, or it could just be a
network issue. Can you try switching all your cables and see if it's any
different?

thanks!

Seb

**Comment by ErikNatanael** [comment]
Good idea, I'll give that a go when I get back to my equipment on Monday. Cheers!

**Comment by ErikNatanael** [comment]
Sorry about the late reply, the new networking hardware took a while to arrive. Initial tests show I'm getting way fewer of these with a new router and a shorter cable to the laser as well so it seems to be related at least!

**Comment by robin-price** [comment]
I'm getting similar bugs with an etherdream 2 but they only occur when I run my ofx code in linux, macos seems to work without interruption. 

Is the vibe that this is a networking issue?

**Comment by robin-price** [comment]
protocol           : 0
When it plays up this is what I get

light_engine_state : ready 0
playback_state     : idle 0
source             : 0
light_engine_flags : 00000
playback_flags     : 011
source_flags       : 0
buffer_fullness    : 0
point_rate         : 0
point_count        : 0

[notice ] sendPrepare()
[notice ] sendBegin()

**Comment by ErikNatanael** [comment]
I'm on Linux as well so that's probably one parameter. Some network implementation detail specific to Linux perhaps?

**Comment by robin-price** [comment]
I've tried it with both a manual static ip and with a spare router, currently running with a router

inxi gives
Network:
Network:
  Device-1: Intel Ethernet I219-V vendor: ASUSTeK driver: e1000e v: 3.2.6-k 
  port: efa0 bus ID: 00:1f.6 
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 



ifconfig config gives
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.100  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::e9e2:cb28:c8e1:6995  prefixlen 64  scopeid 0x20<link>
        ether 04:d4:c4:4d:30:2c  txqueuelen 1000  (Ethernet)
        RX packets 3100681  bytes 247489754 (247.4 MB)
        RX errors 0  dropped 3  overruns 0  frame 0
        TX packets 3140337  bytes 688458581 (688.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0x80600000-80620000

**Comment by sebleedelisle** [comment]
I suspect that it might be something to do with the thread priority - line
153 of ofxLaserDacEtherdream.cpp sets it - do you want to try increasing it
and see if that resolves the issue?

**Comment by robin-price** [comment]
I've tried setting it to 99 still resets loads. It's weird, exact same code base seems fine in macos.

**Comment by sebleedelisle** [comment]
Even just using the basic example? Or are you doing anything more complicated?

**Comment by robin-price** [comment]
Just recompiled basic example and same error persists. I've tried the etherdream wired directly in and static ip and and over router. Lowering the point rate improves things a bit but it still resets just not as often.  I've just fitted the saturn 1 galvos and was enjoying flicker free high point rate.

**Comment by sebleedelisle** [comment]
What point rate are you using? You're definitely not on wifi?

**Comment by sebleedelisle** [comment]
the error is a buffer under-run so for whatever reason the ether-dream
isn't getting points when it needs it. It'll either be a network issue or a
code optimisation issue. You generally don't need to push the point rate
that high because the system can change the speed of the scanners no matter
what the point rate is. It's not like old-school laser software that is
dependent on preset point streams. Hope this helps!

**Comment by robin-price** [comment]
Point rate anything betweeen 45k and 70k seems to give best results, works fine on mac os, anything less seems to flicker when I increase detail even if I fiddle with the speed settings. One thing I'd noticed was in mac install (I'm on a hackintosh) I had internet sharing set from wifi to ethernet but even when I try that in linux it still gives the same errors. I've tried wired direct with manual static ip, wired via router with dhcp and internet sharing and they all seem to give the same problem. I'm starting to wonder if there's something hinky with my mint install ethernet driver.

**Comment by robin-price** [comment]
If you have any tips on how you get best results over ethernet in linux with the ether dream I'm all ears let me know btw, thanks!

**Comment by sebleedelisle** [comment]
So the default scanner settings are pretty conservative so as to
accommodate the lowest common denominator. With Saturns you should be able
to push the speed to 200% but really you'll want to create your own set of
scanner settings. Scanner Settings - EDIT - then save as, it'll make a file
in your bin/data folder. (It's always been my plan to include more presets
for high quality scanners, next time I'm working with the good scanners
I'll make one)

But either way, you shouldn't be getting the network issues. I have a Linux
machine here so I'll do some testing and an optimisation pass but it'll
have to wait until the New Year - hope that's OK!

**Comment by sebleedelisle** [comment]
It seems that there was in fact an issue with ED3 - there was some junk data in the control flags parameter in the point_data which ED2 didn't seem to have a problem with but with ED3 would instantly disconnect! I'm not sure if that's the issue you were encountering but it certainly caused problems here. 

Fixes pushed to main, please test it out and let me know how you get along. 

(BTW there is a dangerous bug in the ED3 firmware that is shipped so make sure to update to the latest one on [ether-dream.com](https://ether-dream.com/downloads.html) )

#32

**Comment by sebleedelisle** [comment]
Although it's much improved I think there are still some weird issues affecting ED3. I'm gonna rewrite the ED code from scratch within a month or two. I'm hoping to add the ability to adjust the latency / buffer, and better recognise poor connection quality

**Comment by sebleedelisle** [comment]
Just to let you know I have given the DAC code a major refactor, and ED3 is working very well now. Check out the dev branch if you want to try it out.
