### ISSUE TITLE
Data Path Run time errors on Mac Mini M1

### ISSUE THREAD

**Issue by eighteight** [sebleedelisle/ofxLaser#34]
of_v0.11.2_osx_release

I ran example_HelloLaser on Intel Mac with no issues. However, on Mac Mini M1 (Rosetta build) it produces the following errors:

```
[ error ] ofAppGLFWWindow: 65544: Cocoa: Failed to find service port for display
2022-02-13 15:39:57.379809+0300 astLaserDebug[82298:6783657] Metal API Validation Enabled
[ error ] ofDirectory: createDirectory(): couldn't create directory ""../MacOS/../../../data/ofxLaser/lasers/"": boost::filesystem::create_directories: Read-only file system: "../MacOS/../../../data/ofxLaser"
[ error ] ofDirectory: createDirectory(): couldn't create directory ""../MacOS/../../../data/ofxLaser/lasers/"": boost::filesystem::create_directories: Read-only file system: "../MacOS/../../../data/ofxLaser"
[ error ] ofDirectory: createDirectory(): couldn't create directory ""../MacOS/../../../data/ofxLaser/lasers/"": boost::filesystem::create_directories: Read-only file system: "../MacOS/../../../data/ofxLaser"
[ error ] ofDirectory: createDirectory(): couldn't create directory ""../MacOS/../../../data/ofxLaser/lasers/"": boost::filesystem::create_directories: Read-only file system: "../MacOS/../../../data/ofxLaser"
[ error ] ofDirectory: createDirectory(): couldn't create directory ""../MacOS/../../../data/ofxLaser/scannerpresets/"": boost::filesystem::create_directories: Read-only file system: "../MacOS/../../../data/ofxLaser"
```
The usual bin/data/ path exists and has all permissions:
![Снимок экрана 2022-02-13 в 15 48 00](https://user-images.githubusercontent.com/542368/153753805-e30a7aa4-7b17-4a97-9e65-db3fbf81fb74.png)

I am wondering about how to fix the "couldn't create directory"/Read-only file system" error. If I call 

```
ofSetDataPathRoot("/Users/USER_NAME/Downloads/of_v0.11.2_osx_release/apps/myApps/astLaser/bin/data");
```
to set the absolute data path in setup(), half of the errors disappear, but still some of them remain.

Thanks for you input.

**Comment by sebleedelisle** [comment]
Seems strange... what OS are you running? Are the permiisions read-only for
that folder?

**Comment by eighteight** [comment]
It's Monterey. The permissions were set manually to read/write by all, but that did not affect the errors.

**Comment by sebleedelisle** [comment]
I'm on an M1 MacBook Air (although on Big Sur) but sadly I can't replicate the issue here. Is it happening on the example projects in the addon?  Have you tried manually adding all the folders that it needs? I'm not in a rush to upgrade to Monterey but I'll let you know if I encounter the same problem when I do.

**Comment by sebleedelisle** [comment]
Oh and perhaps you could create a test project without ofxLaser and try adding and removing directories in the data path to see if it's an issue with your oF set up?

**Comment by sebleedelisle** [comment]
Gonna close this for now, reopen if you get more information, thanks!

**Comment by eighteight** [comment]
I tested this on a Macbook Pro M1 –– no issues. Since I no longer have access to that mac mini m1, let's assume it was a permission problem
