### ISSUE TITLE
linking issue

### ISSUE THREAD

**Issue by r33p** [sebleedelisle/ofxLaser#37]
Hi there !
when I try to compile examples, i get a lot of undefined references, mainly with libusb and svgtiny,
(ubuntu 20.04 and gcc 9)

```
/Sources/of_v0.11.2_linux64gcc6_release/addons/obj/linux64/Release/ofxLaser/libs/laserdocklib/LaserdockDevice.o:LaserdockDevice.cpp:fonction LaserdockDevicePrivate::print() const : erreur : référence à « libusb_get_string_descriptor_ascii » non définie
/Sources/of_v0.11.2_linux64gcc6_release/addons/obj/linux64/Release/ofxLaser/libs/ofxSvgExtra/src/ofxSvgExtra.o:ofxSvgExtra.cpp:fonction ofxSVGExtra::loadFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) : erreur : référence à « svgtiny_create » non définie
```

**Comment by sebleedelisle** [comment]
I must admit I haven't compiled on linux for some time but I think these issues may be solved by including ofxKinnect and ofxSvg libraries in your project. Let me know if that works!

**Comment by r33p** [comment]
Hi Seb,
Thanks a lot ! It worked : the compilation is done, and the app is running !

**Comment by sebleedelisle** [comment]
Ah great news! I'm not really sure why those things don't compile on linux the way I've set them up. 😬
