### ISSUE TITLE
Creating SVG files

### ISSUE THREAD

**Issue by yiids** [sebleedelisle/ofxLaser#39]
Im having trouble creating my own SVG files to use in ofxLaser, I try to make some basic shapes in inkscape, but I can seem to get any of them to display in ofxLaser. Are their any special requirments for the SVG`s to be imported properly?

**Comment by yiids** [comment]
just saw this https://github.com/sebleedelisle/ofxLaser/issues/35 Will try to see if I can export to svgtiny profile

**Comment by yiids** [comment]
May I ask which software you used to create the svg frames in the animation example? I have not found any software oher then adobe animate that can export frames to seperate svgs.. And since I`m on linux I can use adobe animate..

**Comment by sebleedelisle** [comment]
I used Adobe Animate with a super flaky SVG export plug-in. I wouldn't
recommend it. There are slim pickings for vector animation software
unfortunately, but I did have some luck with Keyshape (Mac only I think,
sorry). I would investigate SVG exports from Blender. Or you could see if
there are any animation plugins/capabilities for Inkscape. Let me know how
you get along!

Seb

**Comment by sebleedelisle** [comment]
There's some more background in this video https://www.youtube.com/watch?v=U4D0wJNYtWs
