### ISSUE TITLE
Build errors main branche

### ISSUE THREAD

**Issue by adminfriso** [sebleedelisle/ofxLaser#44]
It might be a mac only problem, but when I try to compile the library using the hello laser example (and also the same in my main project) this class keeps throwing lots of errors. 

<img width="726" alt="Screenshot 2024-02-09 at 11 26 54" src="https://github.com/sebleedelisle/ofxLaser/assets/23073031/1f681d52-8143-4d84-9e99-7be4c608ded3">

**Comment by adminfriso** [comment]
Also, and this might need to be a seperate issue, but i noticed the sendRawPoints requires the zone as an object now, instead of an int. Is it possible to leave the zone and go directly for the laser? or is there a way to retreive the zone instance from the library?

**Comment by sebleedelisle** [comment]
> It might be a mac only problem, but when I try to compile the library using the hello laser example (and also the same in my main project) this class keeps throwing lots of errors.

Apologies, I messed up git. Should be reverted now try again?

**Comment by sebleedelisle** [comment]
> Also, and this might need to be a seperate issue, but i noticed the sendRawPoints requires the zone as an object now, 

The newly reverted code still uses the zone as an index.

**Comment by adminfriso** [comment]
works like a charm. Thank you for your good and fast work :)

**Comment by sebleedelisle** [comment]
Thanks Friso, hope all is well!
