### ISSUE TITLE
change reset flag on full Etherdream DAC buffer

### ISSUE THREAD

**Issue by adminfriso** [sebleedelisle/ofxLaser#45]
Hi Seb we are getting ready for a big show oversea, and we are super exited!  (Check our instagram beginning next week to see what we are up to :) )

We notice that the DAC resets when the buffer gets full. This is very heavy on the shutters of our lasers because when the DAC resets the shutter closes and opens really fast and we got a broken shutter from that, it also happens quite often. When we lower the pps to 20K we can avoid it from being full, but well, who wants a low pps, especially with a DAC that should reach 100Kpps

Is there a way you see fit I can change the resetflag into a clear of the internal buffer so that we wont reset the DAC, but still keep the buffer in check? 

https://github.com/sebleedelisle/ofxLaser/blob/18114c380f8afa70a5fea63b68012c9f00723d69/src/dacs/ofxLaserDacEtherdream.cpp#L537

The DAC will reply with ACK if the incoming packet can fully fit in its buffer, or NAK - Full if it cannot. It is valid for npoints to be zero; in this case, no point will be added to the buffer, but the packet will still be ACKed (as long as the DAC is Prepared or Playing.)

**Comment by adminfriso** [comment]
I tried to add a clearFlag like this, but because the waitForAck notices that the DAC outputs playback_state 0 (idle apparantely) it still restarts the connection. 

<img width="1038" alt="Screenshot 2024-02-15 at 14 52 35" src="https://github.com/sebleedelisle/ofxLaser/assets/23073031/45ae167b-c265-443e-aa54-726cc2b3a460">

This is the status it shows:

protocol           : 0
light_engine_state : ready 0
playback_state     : idle 0
source             : 0
light_engine_flags : 00000
playback_flags     : 000
   shutter         : open
   underflow       : false
   e-stop          : false
source_flags       : 0
buffer_fullness    : 148
point_rate         : 0
point_count        : 236466010

the light engine looks like it is still active, but the shutter looks closed based on the playback state 
```
Similarly, playback_state gives the state of the playback system. The playback_flags field may be nonzero during normal operation. Its bits are defined as follows:

[0]: Shutter state: 0 = closed, 1 = open.
```

I am not sure how to approach this from here on

**Comment by adminfriso** [comment]
Won't need to think further about this, we are just too enthousiast about the pps. Lower it and it's fine. 
Resetting the DAC like this actually is a very safe way, and what I was suggesting is probably not so safe.

**Comment by sebleedelisle** [comment]
Hey Friso, the timing of this wasn't great as I was deep in the middle of Liberation Day! I must admit I don't fully understand the issues you're facing, and the sendRawPoints functionality is very much untested, I suspect you're the only one using it 😅

The DAC system has some complicated engineering to figure out when to send new points, which of course are bypassed completely when using sendRawPoints, but it might be worth taking a look at those to see how I'm doing it under the hood. 

Otherwise there are a lot of competing features and Liberation stuff monopolising my time at the moment and sadly sendRawPoints is very low on the list. But it is something I would like to fix properly in the long term.

**Comment by adminfriso** [comment]
Hey Seb, I hope you had a great Liberation Day. Seen from the newsletter I think you did!

The issue we face with our etherdreams is that they do not accept the 100kpps as that they promised. Not on the hello laser example and not using the raw points system.

The fast solution I was talking about was to not trigger a reset but clear the ofxLaser buffer to give the dac's some space without resetting them. However from what I tried it did not give the intended result.
I think I missed something, or the raw system is working diffrently from how I thought.

In our own system before we send the raw points we also do a rate limit to not exceed the kpps. its a bit raw but it works.
To get a better understanding of what is going on. Where can I see the engineering when to send new points in ofxLaser? 

And it might be good to add that we got some seperation of concern in our adapter to the laser library, so there is a bit more freedom to develop there. I HOPE, that when we have a next show we can test what happens when we directly use the laser library intended functionality instead of sendRawPoints. but I might be speaking ahead of myself.

**Comment by sebleedelisle** [comment]
Have a look in the dev branch at the DacBaseThreaded - there's some logic there for calculating how full the DAC buffer is at any time, and a test to see whether to send a new frame or not. 

I must admit I never go anywhere near as high as 100,000pps, so there may be other optimisation issues? Not sure. For any other usage I would suggest that you would never need such a high point rate but I suspect that is not true in your case 😅
