### ISSUE TITLE
getWarpedPoint is getting 27% of CPU

### ISSUE THREAD

**Issue by Vamoss** [sebleedelisle/ofxLaser#48]
Hi @sebleedelisle,

Thank you again for the amazing addon!

I am playing with hundreds of dots and noticed that `getWarpedPoint` is getting 27% of CPU.

I am willing to skip this function call and scale/translate the points outside the addon.

I also have experience in building warping tools for projection mapping, and instead of using opencv, I shared this base for texture warping. Maybe it could be very usefull for simplifying:
https://stackoverflow.com/questions/16989181/whats-the-correct-way-to-draw-a-distorted-plane-in-opengl/16993202#16993202

Please, let me know your toughts.

**Comment by sebleedelisle** [comment]
Hi @Vamoss, glad it's useful for you! 

Where to start? Is this happening on the examples or on your own code?  

Firstly, getWarpedPoint definitely shouldn't be using that much CPU so not sure why that is happening... If you turn off perspective warping in the zone settings then it disables openCV - can you try that and see if it makes a difference? 

I believe the algorithm you have shared with me is not perspective correction but bilinear interpolation and doesn't always look right. If you turn off the "perspective" option on the zone settings it uses this exact algorithm!

Hope this helps, have a try and let me know what happens. 

Sean

**Comment by Vamoss** [comment]
Thank you for the reply. It is happening on my code.

I didnt knew about the `perspective` option, that is perfect.

Thank you again!

**Comment by sebleedelisle** [comment]
Glad it's sorted but I'm concerned about the CPU usage! What's your system?
Does the problem go away when you switch perspective off ? Thanks!

**Comment by Vamoss** [comment]
I am on Windows with i7 processor. Just to make me clear: The CPU usage I am referring is not the machine total CPU available, but the proportional usage from the software itself. From the total amount of how much CPU the software was using, 29% was just this function `getWarpedPoint`.

I tested it again, and the perspective after the applied distortion, still influencing the whole scene even with it turned OFF. It does not rollback to transform only scale/position after unselected. And I didnt noticed the effect on the FPS with the option ON or OFF.
I can take a look into the code later, but seems to have no effect on the performance.
