### ISSUE TITLE
controller recommendation ?

### ISSUE THREAD

**Issue by robin-price** [sebleedelisle/ofxLaser#50]
Not an issue per se but I've had some minor difficulties with the ether dream 3 in the past and I'm in the process of getting a second laser so I need a new ILDA controller... Do you recommend the 4? Use with ofxLaser with a 7W and some decent either Saturn 1 or 5 galvos is my primary use case so if there's one you recommend?

**Comment by sebleedelisle** [comment]
What issues have you had? I think there may have been some problems with the early firmware - the image would sometimes come out rotated! - but that was quickly solved in an update so make sure you have the latest. 

V4 is pretty much identical to V3, I think just some minor footprint changes but the Ether Dream 4 (or 3)is absolutely the best option right now and I wouldn't hesitate to recommend it.

**Comment by robin-price** [comment]
Thanks, it was using the ether dream 3 in linux, I was getting buffer under runs. I think you fixed it but never had chance to check as I went with a macOS install in the end. Thanks for letting me know, I'll order a 4 !

**Comment by sebleedelisle** [comment]
Ah yeah it hasn't been tested much on linux. Could be a thread priority
issue, or even just if the machine isn't fast and can't keep up.
