### ISSUE TITLE
windows10 vc2017 problem

### ISSUE THREAD

**Issue by liu7055** [sebleedelisle/ofxLaser#7]
![image](https://user-images.githubusercontent.com/14064879/58465646-ba158600-816a-11e9-9ff2-17798c63a213.png)
then have some errors，lack of ofxClipper.h and not include"gl/glu.h"
...............................................................................................................................
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E0757	重载函数 "std::chrono::duration<_Rep, _Period>::duration [其中 _Rep=long long, _Period=std::nano]" 不是类型名	laser	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\chrono	195	
错误(活动)	E0020	未定义标识符 "gluProject"	laser	C:\Users\Robin\Desktop\of_v0.10.0_vs2017_release\addons\ofxLaser\src\ofxLaserManager.cpp	711	
错误	C1083	无法打开包括文件: “ofxClipper.h”: No such file or directory (编译源文件 ..\..\..\addons\ofxLaser\src\ofxLaserGraphic.cpp)	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.h	12	
错误	C3861	“gluProject”: 找不到标识符	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasermanager.cpp	711	
..........................................................................................
then
![image](https://user-images.githubusercontent.com/14064879/58466261-e4b40e80-816b-11e9-8cef-8f9f54673980.png)
and update
ofxClipper link: https://github.com/bakercp/ofxClipper
................................................................................................
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3861	“gluProject”: 找不到标识符	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasermanager.cpp	711	
错误	C2039	“getClippedPolyTree”: 不是“ofx::Clipper”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.cpp	57	
错误	C2039	“getClippedPolyTree”: 不是“ofx::Clipper”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.cpp	99	
错误	C2039	“getClippedPolyTree”: 不是“ofx::Clipper”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.cpp	137	
错误	C2039	“getClippedPolyTree”: 不是“ofx::Clipper”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.cpp	359	
错误	C3861	“gluProject”: 找不到标识符	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\ofxlasergraphic.cpp	412	
.................................................................................................

**Comment by liu7055** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	“clear”: 不是“ofxSVG”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\utils\svgloader.cpp	101

**Comment by liu7055** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	“loadFromData”: 不是“ofxSVG”的成员	laser	c:\users\robin\desktop\of_v0.10.0_vs2017_release\addons\ofxlaser\src\utils\svgloader.cpp	104

**Comment by liu7055** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细说明
错误(活动)	E0757	重载函数 "std::chrono::duration<_Rep, _Period>::duration [其中 _Rep=long long, _Period=std::nano]" 不是类型名	laser	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\chrono	195		          在处理 "std::chrono::time_point" 基于模板参数 <std::chrono::nanoseconds> 所在行数:103，所属文件:"C:\Users\Robin\Desktop\of_v0.10.0_vs2017_release\libs\openFrameworks\utils\ofUtils.h" 的模板参数列表期间检测

**Comment by sebleedelisle** [comment]
Hi there, thanks for letting me know!

There were some broken dependencies that I have now included. For some reason I'm having trouble getting some of the included libs compiled in VS2017 but I'm not familiar enough with VS to troubleshoot the problem. Perhaps you could try it for me and let me know what happens?

**Comment by liu7055** [comment]
Hi, we also tried it on Fedora30 ,commline make  it ,there have some issuses
.......................................................
/home/neo/Documents/Dev/of_v0.10.1/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/neo/Documents/Dev/of_v0.10.1/apps/myApps/myHeroicSketch'
/home/neo/Documents/Dev/of_v0.10.1/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
............................................
It less libusb-1.0 ,I have downland libusb-1.0.lib from laserdock github ,but it didn't work 
......................................
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
..............................................
Could you help me fix those issuses on linux ,thx 
 By the way,i run it on OSX ,it works nice jobs

**Comment by sebleedelisle** [comment]
Hi there, 

Thanks! It now compiles on Windows 10 with VS2017. Unfortunately I don't have a Linux set up to test with but if you have any luck getting it to work, please make a pull request. 

But as this issue is about Windows 10 / VS2017, I'll close this now.
